### ISSUE TITLE
ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by lunzueta** [norse/norse#238] opened 2021-08-17 17:55 UTC
**Describe the bug**
I get the following error when I install Norse from PyPi on a desktop PC (x64) with Windows 10: "ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly". If I install it from Conda it installs v0.0.3 (noarch) instead of v0.0.6 (win-64).

I have tried this in Anaconda environments with Python 3.7, 3.8, and 3.9.

**To Reproduce**
From a Conda environment write: `pip install norse`

**Expected behavior**
You get this error: "ERROR: Could not build wheels for norse which use PEP 517 and cannot be installed directly".

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by cpehle** [comment] 2021-08-18 10:49
Thanks for bringing up this issue, could you please try to install from source by cloning the repository 
```
pip install -qU git+https://github.com/norse/norse
```
We test installation on Windows in the following GitHub workflow: 
```
https://github.com/norse/norse/blob/master/.github/workflows/pythonpackage.yml
```
So at least that should work on windows. @Jegp do you know anything about the conda package situation?

**Comment by lunzueta** [comment] 2021-08-18 16:30
> 
> 
> Thanks for bringing up this issue, could you please try to install from source by cloning the repository
> 
> ```
> pip install -qU git+https://github.com/norse/norse
> ```
> 
> We test installation on Windows in the following [GitHub workflow](https://github.com/norse/norse/blob/master/.github/workflows/pythonpackage.yml). So at least that should work on windows. @Jegp do you know anything about the conda package situation?

I get the same error. Maybe it's a problem with the building configuration. I have tried installing Visual Studio 2019 Python and C++, and also Build Tools for Visual Studio, but nothing.

I didn't know the GitHub workflow. It's supposed that there is a hosted Windows machine where all this is tested, right? I've tried to find the building configuration of that machine, but I didn't find anything about it.

I've also tried to google about this kind of error for other libraries but the proposed solutions don't work in this case.

**Comment by cpehle** [comment] 2021-08-18 16:51
It might be related to the pip version that you use, at least according to the answers that can be found on [StackOverflow] (https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe). Can you please post the output of
```
pip --version
```

**Comment by lunzueta** [comment] 2021-08-18 17:27
> 
> 
> Thanks for bringing up this issue, could you please try to install from source by cloning the repository
> 
> ```
> pip install -qU git+https://github.com/norse/norse
> ```
> 
> We test installation on Windows in the following [GitHub workflow](https://github.com/norse/norse/blob/master/.github/workflows/pythonpackage.yml). So at least that should work on windows. @Jegp do you know anything about the conda package situation?

I get the same error. Maybe it's a problem with the building configuration. I have tried installing Visual Studio 2019 Python and C++, and also Build Tools for Visual Studio, but nothing.

I didn't know the GitHub workflow. It's supposed that there is a hosted Windows machine where all this is tested, right? I've tried to find the building configuration of that machine, but I didn't find anything about it.

I've also tried to google about this kind of error for other libraries but the proposed solutions don't work in this case.

**Comment by cpehle** [comment] 2021-08-18 17:29
Did that help?

**Comment by lunzueta** [comment] 2021-08-18 17:30
> 
> 
> It might be related to the pip version that you use, at least according to the answers that can be found on [StackOverflow](https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe). Can you please post the output of
> 
> ```
> pip --version
> ```
> 
> also in the GitHub workflow the first thing we run is
> 
> ```
>  pip install --upgrade pip
> ```

Yep. That's one of those things I found to solve this PEP 517 error, but it didn't work.

```
Requirement already satisfied: pip in c:\users\l_u_i\anaconda3\lib\site-packages (21.2.4)
Requirement already satisfied: wheel in c:\users\l_u_i\anaconda3\lib\site-packages (0.37.0)
Requirement already satisfied: setuptools in c:\users\l_u_i\anaconda3\lib\site-packages (57.4.0)
```

**Comment by lunzueta** [comment] 2021-08-18 17:31
OMG. I don't know how I did it but I closed this accidentally, sorry...

**Comment by cpehle** [comment] 2021-08-18 17:32
Not a problem, I was just confused, because if there is a problem on windows, we definitely want to fix it 🙂.

**Comment by lunzueta** [comment] 2021-08-18 17:33
> 
> 
> Not a problem, I was just confused, because if there is a problem on windows, we definitely want to fix it 🙂.

That's great, thanks 👍

**Comment by lunzueta** [comment] 2021-08-18 17:48
I've also tried with Miniconda instead of Anaconda, but it didn't work either (Python 3.9).

**Comment by lunzueta** [comment] 2021-08-18 18:15
I've read [here](https://qutip.org/docs/latest/installation.html) that there are builders compatible with PEP 517, like [build](https://pypi.org/project/build/), but I see that installing this is not enough to solve this issue.

**Comment by Jegp** [comment] 2021-08-18 19:00
Thanks for sticking with us @lunzueta! As @cpehle said, we're keen on fixing this.

Regarding the conda situation, it's been challenging to create reproducible builds because Torch is such a beast to build. But we've recently pushed newer unit tests for Windows, which should make it easier to get conda to play nice (([the config is here](https://github.com/norse/norse/blob/master/.github/workflows/pythonpackage.yml#L12) if you're interested @lunzueta). I'll give it a stab and try to reproduce it now.

**Comment by lunzueta** [comment] 2021-08-19 07:32
I also get this PEP 517 error when installing the pytype dependency. The rest of the modules are installed normally. It's only something related to the PEP 517 build. Maybe using another builder, like the one I mentioned before would fix this?

**Comment by Jegp** [comment] 2021-08-19 19:29
It would still be nice to get conda working, because it seems like a good solution for Windows. I just don't understand why it's failing. It seems to me there's something fishy with conda-build, so I opened an issue here https://github.com/conda/conda-build/issues/3246

For now, I think I'll settle with trying to get a working pip installation with your suggestion. Hang tight!

**Comment by AlmaLuna94** [comment] 2021-08-20 09:12
I also had/have the same issue when i tried installing Norse on my Windows computer. I tried similar ways to fix it as the ones you have written above. The only way I managed to get it to work was by using Docker and a simulated Linux environment. Although, that was a while ago and right now I am only using Norse on my Linux workstation.

**Comment by AlmaLuna94** [comment] 2021-08-20 09:13
I will try again now that you "Updated pypi and conda build and bumped torch version requirement". Hopefully it works now!

**Comment by Jegp** [comment] 2021-08-20 09:22
It's fascinating to hear it's such a problem. It's so hard to test when I don't have access to a native Windows machine :-/

The pypi code hasn't been pushed yet, but when we merge the branch, it *should* be as simple as `pip install norse` on Windows. Fingers crossed! :crossed_fingers:  :)

**Comment by lunzueta** [comment] 2021-08-20 11:17
Meanwhile, I'm using Norse directly in WSL 2, (no Docker, no GPU). The problem is that if I want to use the GPU, in the end, it should run natively on Windows (there are some alternatives but they are very complicated and not always possible; register to the Windows Insider Program to download a beta version of Windows, install some experimental drivers for NVIDIA, etc). For normal Windows users to solve this PEP 517 issue would be the best. Thanks for you efforts.

**Comment by Jegp** [comment] 2021-08-21 13:21
Unfortunately, that didn't fix the issue. The windows build fails when creating a virtual environment: https://github.com/norse/norse/runs/3389115902?check_suite_focus=true

In general, I don't have any good way of debugging this. If anyone has any inputs/ideas on how to reproduce this, I'm eager to hear their ideas!

**Comment by lunzueta** [comment] 2021-08-21 15:21
Hey! There's still some hope. I've been able to compile it, even though not in an "elegant way". Take a look at my changes [here](https://github.com/lunzueta/norse/commit/2bcd8955c92eb375d77569c19563fdea4a5223cf). To get there I've just fixed every error I was receiving while debugging `python setup.py install`. First, the `set_win_env.bat` file must be run, so that the appropriate cl.exe is configured and DISTUTILS_USE_SDK=1 is set (don't know what it is for but the system was asking for it). Then, `python setup.py install` and that's it. Not sure how to put it in a better way.

**Comment by Jegp** [comment] 2021-08-21 19:32
Great news! Specifically, I'm looking for a way that we can *automate* this building, so we can forget everything about it and leave it running every time we push a new version of Norse.

I see two paths ahead: I'm happy to take your suggestions and try to implement it. That will, hopefully, work :)
I'm also more than happy to accept a contribution from you in the form of a pull request. It doesn't have to be huge. But if you can write down the exact steps you took (including various scripts like you mention) and write them down in our GitHub workflow for either [pip](https://github.com/norse/norse/blob/master/.github/workflows/publish_pypi.yml) or [conda](https://github.com/norse/norse/blob/master/.github/workflows/publish_conda.yml) that would be a tremendous contribution. I think you'll save many hours of debugging for me, at least :)

**Comment by Jegp** [comment] 2021-08-21 19:33
You're also more than welcome to drop by our chat and talk it through with us :) https://discord.gg/7fGN359

**Comment by lunzueta** [comment] 2021-08-22 07:11
> 
> 
> Great news! Specifically, I'm looking for a way that we can _automate_ this building, so we can forget everything about it and leave it running every time we push a new version of Norse.
> 
> I see two paths ahead: I'm happy to take your suggestions and try to implement it. That will, hopefully, work :)
> I'm also more than happy to accept a contribution from you in the form of a pull request. It doesn't have to be huge. But if you can write down the exact steps you took (including various scripts like you mention) and write them down in our GitHub workflow for either [pip](https://github.com/norse/norse/blob/master/.github/workflows/publish_pypi.yml) or [conda](https://github.com/norse/norse/blob/master/.github/workflows/publish_conda.yml) that would be a tremendous contribution. I think you'll save many hours of debugging for me, at least :)

It will be my first time with Github workflow, but I can try :-)

**Comment by lunzueta** [comment] 2021-08-22 07:43
Mmmmm, according to [this](https://docs.github.com/es/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) it looks like I can't test the updated workflow by myself, I think we should do it together. I found [this](https://github.com/nektos/act) that would allow me to test the workflow locally, but unfortunately not for a Windows machine. I'll send a pull request and then we might continue from there.

**Comment by Jegp** [comment] 2021-08-22 08:36
Excellent @lunzueta, thanks a lot for your help!

Indeed, it seems like the continuous integration workflows on Windows are somewhat behind. I'll have a look at your PR. I'm hoping we can just look at it really long and get it working in the first run ;-)

**Comment by Jegp** [comment] 2021-08-23 20:41
Well. That didn't work :disappointed: 
https://github.com/norse/norse/runs/3404658884?check_suite_focus=true
```Run python3 -m build -o dist .
* Creating venv isolated environment...
...
FileNotFoundError: [WinError 2] The system cannot find the file specified

ERROR [WinError 2] The system cannot find the file specified
Error: Process completed with exit code 1.
```

**Comment by Jegp** [comment] 2021-08-23 20:56
I won't have time to look at this in detail the next couple of days, unfortunately. But following that, I'll try to have an intimate session with someone else's windows laptop to sort this out.

**Comment by Jegp** [comment] 2022-01-05 20:09
Unless there's any news on this, I suggest closing this issue. I'm adding new CI checks for all platforms, but it's beyond me to thoroughly test Norse on Mac and Windows, unfortunately. I'm grateful if anyone else feels like volunteering :-)

**Closed by Jegp** 2022-01-05 20:09 UTC
Labels: bug, installation, windows
