### ISSUE TITLE
Problems encountered during installation

### ISSUE THREAD

**Issue by yjzhang97** [norse/norse#312] opened 2022-04-14 10:47 UTC
conda install norse

norse version 0.0.7.post1

Cuda  release 10.2, V10.2.89

torch.__version__  '1.11.0'

OS: Ubuntu 20.04.3 LTS

When I import norse in ipython after installation:
```python
~/anaconda3/envs/torch/lib/python3.8/site-packages/norse/torch/functional/lif.py in <module>
     33 
     34 try:
---> 35     import norse_op
     36 except ModuleNotFoundError:  # pragma: no cover
     37     pass

ImportError: /home/yjzhang/anaconda3/envs/torch/lib/python3.8/site-packages/norse_op.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

In [2]: import norse_op
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6416f71b9b12> in <module>
----> 1 import norse_op

ImportError: /home/yjzhang/anaconda3/envs/torch/lib/python3.8/site-packages/norse_op.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

```

**Comment by Jegp** [comment] 2022-04-14 21:00
Thanks for bringing this to our attention!

It looks like it can't find the correct PyTorch installation. Could you try to install PyTorch manually and then try to reinstall Norse? https://pytorch.org/get-started/locally/

Separately, I've had a lot of hassle with Conda builds, but I recently retrofitted the master branch to *hopefully* work with Conda. If the above doesn't work, could you try installing Norse directly from master? Something like this should do the trick:

`pip install git+https://github.com/norse/norse`

**Comment by cpehle** [comment] 2022-04-15 11:54
Do you think there might be a way to catch this in CI? I also encountered this error in a non-reproducible way and wasn't really sure how to fix it.

**Comment by ggoupy** [comment] 2022-04-16 15:16
> Thanks for bringing this to our attention!
> 
> It looks like it can't find the correct PyTorch installation. Could you try to install PyTorch manually and then try to reinstall Norse? https://pytorch.org/get-started/locally/
> 
> Separately, I've had a lot of hassle with Conda builds, but I recently retrofitted the master branch to _hopefully_ work with Conda. If the above doesn't work, could you try installing Norse directly from master? Something like this should do the trick:
> 
> `pip install git+https://github.com/norse/norse`

I had the same issue, installing manually the lastest version of pytorch and then norse with `pip install git+https://github.com/norse/norse` did the job !

Thanks

**Comment by Jegp** [comment] 2022-04-18 20:27
Thanks for the input @ggoupy. I'm trying to get better automated builds so we can (hopefully) solve this for perpetuity.

Did you manage to solve it @yjzhang97? :)

**Comment by cpehle** [comment] 2022-04-19 19:46
Should we close this issue for now? We can perhaps add a clarifying section in the installation section on it.

**Comment by yjzhang97** [comment] 2022-04-20 01:32
I thy to create a new python environment with conda, then I install PyTorch manually and  install Norse through conda .
It looks like working fine.
Thank you.

**Comment by Jegp** [comment] 2022-04-21 09:03
It's a common problem and I actually added a FAQ section here: https://norse.github.io/norse/pages/installing.html#installation-troubleshooting

We'll keep an eye on it and see if we can find a better, and more permanent, solution.

Thanks for getting back to us. Feel free to reopen if you run into other issues.

**Closed by Jegp** 2022-04-21 09:03 UTC
Labels: bug, C++
