### ISSUE TITLE
Shared Lib issues relating to norse_op with norse > 0.0.7 

### ISSUE THREAD

**Issue by Surya-77** [norse/norse#280] opened 2021-12-17 08:40 UTC
Trying to upgrade norse to test new features in 0.0.7 results in errors with shared libraries relating to "norse-op"

Created a new environment and installed from source.

ERROR: python3.8/site-packages/norse_op.so: undefined symbol: _ZN2at4_ops3abs4callERKNS_6TensorE
Unexpected error from trying to import norse-op.so

ENV: 
Description:    Ubuntu 20.04.3 LTS
Python 3.8.3
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

Not sure if this is build error or python error.
The only other issue related to this that i was able to find is #184 
I would really like your assistance with this one.

**Comment by cpehle** [comment] 2021-12-17 09:27
Thanks for reporting this issue, I actually encountered the same a few days ago and have not had time to investigate.

**Comment by Jegp** [comment] 2021-12-18 21:31
Thanks for reporting this. I can't seem to reproduce it with the environment you describe. We do, though, have continuous builds to ensure the installation works, so I'm very curious to understand what's wrong. Did you install PyTorch independently before you installed Norse? Are you doing a `pip install -e .` or `pip install git+https...`?

**Comment by Surya-77** [comment] 2021-12-19 07:52
Regarding the installation process. I tried with direct git install from pip as well as using the pip repository version. Both failed to run. The norse_op.so file exists in both versions and has the correct permissions.

Regarding the pytorch environment. Here's the details from conda. I believe i
pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
torchaudio                0.9.0                      py38    pytorch
torchvision               0.7.0                    pypi_0    pypi
 
Hope this helps. Thanks for the support.

**Comment by asselkembay** [comment] 2021-12-22 08:39
> 

Hi, I got the same error, like:
```Traceback (most recent call last):
  File "1.py", line 2, in <module>
    import norse
  File "/home/.local/lib/python3.8/site-packages/norse/__init__.py", line 4, in <module>
    from . import benchmark, dataset, task, torch, utils
  File "/home/.local/lib/python3.8/site-packages/norse/torch/__init__.py", line 7, in <module>
    from .models import *
  File "/home/.local/lib/python3.8/site-packages/norse/torch/models/__init__.py", line 1, in <module>
    from .conv import ConvNet, ConvNet4
  File "/home/.local/lib/python3.8/site-packages/norse/torch/models/conv.py", line 3, in <module>
    from norse.torch.functional.lif import LIFParameters
  File "/home/.local/lib/python3.8/site-packages/norse/torch/functional/__init__.py", line 5, in <module>
    from .adjoint.lif_adjoint import (
  File "/home/.local/lib/python3.8/site-packages/norse/torch/functional/adjoint/lif_adjoint.py", line 4, in <module>
    from norse.torch.functional.lif import (
  File "/home/.local/lib/python3.8/site-packages/norse/torch/functional/lif.py", line 35, in <module>
    import norse_op
```
But what I did was:
1. pip uninstall norse
2. pip install -qU git+https://github.com/norse/norse
It has solved the error.

**Comment by Surya-77** [comment] 2021-12-22 08:54
Unfortunately i tried this method already, and it did not work for me.

**Comment by asselkembay** [comment] 2021-12-22 09:09
> Unfortunately i tried this method already, and it did not work for me.
![image](https://user-images.githubusercontent.com/82306310/147066850-e48b2c62-d0c1-4b7f-a462-cf3a5ba91f85.png)

As you can see I had a working Norse, but I got the same error after installing them and that actually gave an Error(red lines)

**Comment by asselkembay** [comment] 2021-12-22 09:11
> > Unfortunately i tried this method already, and it did not work for me.
> > ![image](https://user-images.githubusercontent.com/82306310/147066850-e48b2c62-d0c1-4b7f-a462-cf3a5ba91f85.png)
> 
> As you can see I had a working Norse, but I got the same error after installing them and that actually gave an Error(red lines)

After uninstalling them and installing again Norse(with a requirable torch) it works. Hope it helps 
![image](https://user-images.githubusercontent.com/82306310/147067283-4386085c-4d5f-4666-b15b-7cc072843cd0.png)

**Comment by Surya-77** [comment] 2021-12-22 10:35
Thanks for your help @asselkembay

Issue might be due to torch distribution needing to be rebuilt along with norse.?.

So to summarize:

1. Uninstall existing norse distribution AND torch dependencies. [In case of upgrade]
2. Install norse with dependencies. [Used pip repo for installation]
    This results in torch-cpu being installed. 
4. Uninstall torch-cpu or directly upgrade to torch-cuda versions as needed.
5. Installation loads norse package successfully without any errors.

**Comment by Jegp** [comment] 2021-12-22 18:48
Thanks for all your inputs! I'm honestly puzzled by this. If Torch isn't present, then it should be installed via pip since it's a dependency. However, if it's already there, there should be absolutely no need to uninstall, only to upgrade it to the CUDA version afterwards. I'll try to reproduce it in a containerized environment. If you have any more pointers, I'm eager to hear about them :-)

**Comment by Jegp** [comment] 2021-12-22 19:44
I wasn't able to reproduce with in either 3.8 or 3.9 with CPU _or_ GPU installations. Could you kindly verify that 
1. Your `pip` installation is up to date? (`pip install --upgrade pip`)
2. You had a working torch version _before_ you installed Norse?

I'm not really sure where the error comes from, but I'm keen to figure out!

**Comment by asselkembay** [comment] 2021-12-23 01:24
> I wasn't able to reproduce with in either 3.8 or 3.9 with CPU _or_ GPU installations. Could you kindly verify that
> 
> 1. Your `pip` installation is up to date? (`pip install --upgrade pip`)
> 2. You had a working torch version _before_ you installed Norse?
> 
> I'm not really sure where the error comes from, but I'm keen to figure out!

Good day! 
1. 
```
:~$ pip install --upgrade pip
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 11.0 MB/s 
Installing collected packages: pip
Successfully installed pip-21.3.1
```
2. Yes I had a working Norse+torch too, I got the Error after installing this :
```
!pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
!pip install torchtext==0.9.1
```
During the installation was occured this: 
![image](https://user-images.githubusercontent.com/82306310/147173193-4eed06a8-9521-467b-b5e0-f1d883f15699.png)
I think this is an issue here. But after the doing above lines of work, now, Norse works well again.

**Comment by Jegp** [comment] 2021-12-29 16:36
Thanks for your comments @Surya-77 and @asselkembay. I'm not sure to proceed from here. I can't reproduce it in any of the combinations I've tried so far (with and without GPU). We do have a lower bound on the PyTorch version for 1.9 because we're relying on newer features for parts of Norse, so that part isn't so mysterious to me.

Is there any way you can provide steps to reproduce the problem? If not, I would suggest we close the issue for now. You're always welcome to re-open it later! :-)

**Comment by alperyeg** [comment] 2021-12-29 17:36
Unfortunately, I have the same problem. Removing torch, norse and installing it via `pip install norse` creates the aforementioned issue. The second method with `pip install -qU git+https://github.com/norse/norse` is not successful either. To make things little more complicated I also tried `pip install norse==0.07` (note `.post1` is removed) which lead to compilation issues: 
>   norse/csrc/op.cpp:6:10: fatal error: super.h: No such file or directory
      6 | #include "super.h"
        |          ^~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1

My system is a  `5.4.163-1-MANJARO x86_64`, `python3.9`, `gcc 11.1.0`, I am installing within a virturalenv, I don't have a GPU in this system. 
Installing norse via conda works perfectly fine.

**Comment by Jegp** [comment] 2021-12-29 20:41
The plot thickens. I tried to reproduce it in a Manjaro Linux Docker container (Python 3.9.9-1, gcc 11.1.0, kernel 5.11) with the following three setups:
* `pacman -S python-pip && pip install norse`
* `pacman -S python-virtualenv && virtualenv norse && source norse/bin/activate && pip install norse`
* `pacman -S python && python -m venv norse && source norse/bin/activate && pip install norse`

All three worked flawlessly. I also tried to install an version 1.9 of PyTorch before installing Norse, which also seemed ok. What's the missing link here? The container must be different than your setup, but I struggle to see how. Could there be some remnant of an old pytorch version somewhere? Could I perhaps ask you to try to force-remove any old dependencies (`pip uninstall torch norse`) and try to reinstall without any caching (`pip install --no-cache-dir norse`)?

I'm also curious if you have other ideas where the error may occur. Or how I can reproduce it! :)

**Comment by Surya-77** [comment] 2021-12-30 03:19
Apologize for the late replies here. It definitely has to do with some sort of preexisting torch non-cpu binaries.

Prior to installation of norse-0.0.7.post1 :

norse                     0.0.6                     dev_0    <develop>
pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
torchaudio                0.9.0                      py38    pytorch
torchvision               0.7.0                    pypi_0    pypi

Post successful installation :

norse                     0.0.7.post1              pypi_0    pypi
pytorch                   1.10.1          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch                     1.10.1                   pypi_0    pypi
torchaudio                0.10.1               py38_cu102    pytorch
torchvision               0.11.2                   pypi_0    pypi

I believe torch-gpu versions don't come with certain .so files required for norse-0.0.7.post1
So any attempt to install norse without removing my existing torch installation failed.
Only after purging torch dependencies and reinstalling along with the norse package did the installation compete. 
Even then it installed torch-cpu by default and i had to install torch-gpu later.

**Comment by Jegp** [comment] 2021-12-30 11:52
Thanks for the comment @Surya-77. If it indeed is a problem of "leftover" PyTorch versions, then I'm uncertain if it should be within the scope of Norse to resolve that. Also, the default PyTorch installation is probably CPU based. We could add a sub-package in the setup as something like `norse[gpu]`, but the Python setuptools have troubles handling this kind of "dependency branching". We tried to resolve this by explicitly stating PyTorch as a *dependency*. That means it's up to the user to have the correct CPU/GPU/whatever-based PyTorch version installed.

Did you try to 1) purge torch, 2) install the torch GPU version, and 3) install norse? In that case, pip **should** respect the installed version of torch.

**Comment by alperyeg** [comment] 2021-12-30 13:32
I can confirm that having any left-over torch libraries (for me it was torchvision) caused the problem. After removing anything related to torch I did a new install and could successfully import norse. 
Only removing torch is not enough which should be mentioned in the PR #286 as well if not done already.

**Comment by cpehle** [comment] 2021-12-30 15:15
We should perhaps make this even more clear than we are doing currently. Installing torch is unfortunately not entirely standard. So this leaves us in this awkward position, where we can fully specify all dependencies.

**Comment by Jegp** [comment] 2021-12-31 16:34
> We should perhaps make this even more clear than we are doing currently. Installing torch is unfortunately not entirely standard. So this leaves us in this awkward position, where we can fully specify all dependencies.

Agreed. I tried to address exactly this in #286. Both by improving the installation instructions, but also by adding a FAQ/common issues-section in the docs. Should we add/amend something?

The PR is still a draft because I'd like a final confirmation from @Surya-77 to say that this is indeed the case.

**Comment by Surya-77** [comment] 2022-01-04 06:00
In my case, it was indeed related to torch. Since complete uninstallation of existing torch (including all torch stack dependencies) prior to installation of norse-0.0.7post1 was successful. So I guess we can close this issue then.

**Comment by Jegp** [comment] 2022-01-04 20:14
Thanks for getting back to us @Surya-77. I'll close the issue for now. Please don't hesitate to reopen or let us know if you experience anything similar in the future.

Also, if you have a minute, I'd appreciate it if you could gloss over #286 and see whether the changes adequately covers your case. Comments and commits are welcome!

**Closed by Jegp** 2022-01-04 20:14 UTC
Labels: bug, installation

**Comment by Surya-77** [comment] 2022-01-05 09:00
Thanks for resolving the build problems. PR #286 still has some installation issues on a fresh install. I have added linked errors as a comment.  I don't think it is a local issue and it might be worth looking into.

**Comment by Jegp** [comment] 2022-01-05 11:13
Thanks a bunch! Let's continue the conversation in the PR.

**Comment by feitang0** [comment] 2022-08-03 02:48
I found that installing by pip requires gcc >= 9. My previous gcc version was gcc-5, and using pip would cause compiling errors.

**Comment by yuxuan-z19** [comment] 2022-10-17 09:08
Good day. I met a similar problem with `torch==1.14.0.dev20221016+cu117` + `norse==0.0.7.post1` from source. Is there any way to solve it **without changing the CUDA driver** (CUDA 11.7)

```bash
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [1], line 2
      1 import torch
----> 2 import norse
      4 model = norse.torch.SequentialState(
      5     norse.torch.LIF(),
      6     torch.nn.Linear(2, 1)
      7 )

File ~/benchmark/models/.venv/lib/python3.8/site-packages/norse/__init__.py:4
      1 """Norse is a library for doing deep learning with spiking neural networks.
      2 """
----> 4 from . import benchmark, dataset, task, torch, utils
      6 __all__ = ["benchmark", "dataset", "task", "torch", "utils"]
      8 __version__ = "0.0.7"

File ~/benchmark/models/.venv/lib/python3.8/site-packages/norse/torch/__init__.py:7
      1 """Norse is a library for doing deep learning with spiking neural networks.
      2 
      3 This package contains modules that extends PyTorch with spiking neural
      4 network functionality.
      5 """
----> 7 from .models import *
      8 from .module import *
...
---> 35     import norse_op
     36 except ModuleNotFoundError:  # pragma: no cover
     37     pass

ImportError: /home/zyx/benchmark/models/.venv/lib/python3.8/site-packages/norse_op.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
```
